tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/urls.py
from django.conf.urls import url
from . import views

app_name = 'consumer_datapoint'
urlpatterns = [
#Function Based URLS
    url(r'^$', views.consumer_datapoint, name='consumer_datapoint'),
    url(r'^datapoint/$', views.datapoints, name='datapoints'),
    url(r'^datapoint/(?P<dppk>[0-9]+)$', views.datapoint, name='datapoint'),
    url(r'^datapoint/create$', views.create_datapoint, name='create_datapoint'),
    url(r'^datapoint/delete/(?P<dppk>[0-9]+)$', views.delete_datapoint, name='delete_datapoint'),
    url(r'^datapoint_group/$', views.datapoint_group, name='datapoint_group'),
    url(r'^profile/$', views.profile, name='profile'),
    # url(r'^$', views.consumer_datapoint, name='consumer_datapoint'),
    # url(r'^(?P<user_id>[0-9]+)$', views.consumer_datapoint, name='consumer_datapoint'),
    # url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^(?P<account_name>[\w\-]+)/(?P<pk>[0-9]+)$', views.UserAccountLandingView.as_view(), name='user_account'),
    # url(r'^datapoints$', views.DataPointsView.as_view(), name='datapoints'),
    # url(r'^datapoint/(?P<pk>[0-9]+)$', views.DataPointView.as_view(), name='datapoint'),
    # url(r'^datapoint/create$', views.CreateDataPointView.as_view(), name='create_datapoint'),
    # url(r'^datapoint_groups$', views.DataPointGroupsView.as_view(), name='datapoint_groups'),
    # url(r'^datapoint_group/(?P<pk>[0-9]+)$', views.DataPointGroupView.as_view(), name='datapoint_group'),
    # url(r'^datapoint_group/create$', views.CreateDataPointGroupView.as_view(), name='create_datapoint_group'),
    # url(r'^profiles$', views.ProfilesView.as_view(), name='profiles'), #AKA consumer_datapoint
    # url(r'^profile/(?P<pk>[0-9]+)$', views.ProfileView.as_view(), name='profile'),
    # url(r'^profile/create$', views.CreateDataPointGroupView.as_view(), name='create_profile'),


#Class Based URLS
    # url(r'^$', views.ConsumerDataPointView.as_view(), name='consumer_datapoint'),
    # url(r'^login/$', views.LoginView.as_view(), name='login'),
    # url(r'^(?P<account_name>[\w\-]+)/(?P<pk>[0-9]+)$', views.UserAccountLandingView.as_view(), name='user_account'),
    # url(r'^datapoints$', views.DataPointsView.as_view(), name='datapoints'),
    # url(r'^datapoint/(?P<pk>[0-9]+)$', views.DataPointView.as_view(), name='datapoint'),
    # url(r'^datapoint/create$', views.CreateDataPointView.as_view(), name='create_datapoint'),
    # url(r'^datapoint_groups$', views.DataPointGroupsView.as_view(), name='datapoint_groups'),
    # url(r'^datapoint_group/(?P<pk>[0-9]+)$', views.DataPointGroupView.as_view(), name='datapoint_group'),
    # url(r'^datapoint_group/create$', views.CreateDataPointGroupView.as_view(), name='create_datapoint_group'),
    # url(r'^profiles$', views.ProfilesView.as_view(), name='profiles'), #AKA consumer_datapoint
    # url(r'^profile/(?P<pk>[0-9]+)$', views.ProfileView.as_view(), name='profile'),
    # url(r'^profile/create$', views.CreateDataPointGroupView.as_view(), name='create_profile'),

    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

tutorials/virtual_env/virtual_env_dir-01/site_v1/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # # ex: /polls/
    # url(r'^$', views.index, name='index'),
    # # ex: /polls/5/
    # url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

tutorials/virtual_env/virtual_env_dir-01/site_v1/site_v1/urls.py
# from django.conf.urls import url
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^login/',views.login_user),
    url(r'^logout/',views.logout_user),
    # url(r'^',include('django.contrib.auth.urls')),
    url(r'^consumer_datapoint/', include('consumer_datapoint.urls')),
    url(r'^admin_secret_url/', admin.site.urls),
]

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from fernet_fields import EncryptedTextField
from django_localflavor_us.models import USStateField
# from . import admin

# Create your models here.
class Account(models.Model):
    account_name = models.CharField(max_length=64)
    is_active = models.BooleanField(default=False)
    date_joined = models.DateTimeField('date joined')
    license_expires = models.DateTimeField('license expires')
    def __unicode___(self):
        return self.account_name

class UserAccount(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    account_id = models.ForeignKey(Account, on_delete=models.CASCADE)
    user_is_account_admin = models.BooleanField(default=False)
    def __unicode__(self):
        return self.id

class Consumer(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    ssn = EncryptedTextField()
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    date_of_birth = models.DateTimeField('date of birth')
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address1 =  models.CharField(("address1"), max_length=128)
    address2 =  models.CharField(("address2"), max_length=128, blank=True)
    city = models.CharField(("city"), max_length=64)
    state = USStateField(("state"))
    zip_code = models.CharField(("zip code"), max_length=5)
    def __unicode__(self):
        return (self.last_name+" "+self.first_name)

class DataPoint(models.Model):
    ANSWER_TYPE_CHOICES = (
        ('T', 'Text'),
        ('R', 'Radio'),
        ('D', 'DropDown'),
        ('C', 'Checkbox'),
    )
    datapoint = models.CharField(max_length=1028)
    answer_type = models.CharField(max_length=1, choices=ANSWER_TYPE_CHOICES)
    options = models.CharField(max_length=1028, blank=True, default='')
    def __unicode__(self):
        return self.datapoint

class ConsumerDataPoint(models.Model):
    consumer_id = models.ForeignKey(Consumer, on_delete=models.CASCADE)
    datapoint_id = models.ForeignKey(DataPoint, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name="created_by", on_delete=models.CASCADE)
    last_modified_by = models.ForeignKey(User, related_name="last_modified_by",on_delete=models.CASCADE)
    answer = models.CharField(max_length=512)
    remark = models.CharField(max_length=512)
    created_date_time = models.DateTimeField('created date time')
    last_modified_date_time = models.DateTimeField('last modified date time')
    def __unicode__(self):
        return (self.consumer_id+"- "+self.datapoint_id+": "+self.answer)

class DPGroup(models.Model):
    datapoint_id = models.ForeignKey(DataPoint, on_delete=models.CASCADE)
    group_name = models.CharField(max_length=64)
    def __unicode__(self):
        return self.group_name

class DataPointDPGroup(models.Model):
    dp_group_id = models.ForeignKey(DPGroup, on_delete=models.CASCADE)
    datapoint_id = models.ForeignKey(DataPoint, on_delete=models.CASCADE)
    def __unicode__(self):
        return (self.id+" "+self.db_group_id)

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/forms.py
from django.forms import ModelForm
from .models import DataPoint
# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Layout, Submit

class DataPointForm(ModelForm):
    class Meta:
        model = DataPoint
        fields = ('datapoint','answer_type','options')
    #
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #
    #     self.helper = FormHelper
    #     self.helper.form_method = 'post'
    #     self.helper.layout = Layout(
    #         'datapoint',
    #         'answer_type',
    #         'options',
    #         Submit('submit','Submit')
    #     )

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render, redirect
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Account, UserAccount, DataPoint
from django.forms import ModelForm
from .forms import DataPointForm


@login_required
def consumer_datapoint(request):
    return render(request, 'consumer_datapoint/consumer_datapoint.html',{
        'username':request.user.username,
        'logo': 'M-PSYCH',
        'page':consumer_datapoint.__name__,
        'app_links':["datapoint", "datapoint_group", "profile"],
        'login':"logout",
    })

@login_required
def datapoints(request):
    datapoint_list = DataPoint.objects.all()
    return render(request, 'consumer_datapoint/datapoints.html',{
        'username':request.user.username,
        'logo': 'M-PSYCH',
        'page':datapoints.__name__,
        'app_links':["create"],
        # 'app_link_urls':["create_form","delete_action"],
        'login':"logout",
        'datapoint_list':datapoint_list,
    })

@login_required
def datapoint(request, dppk):
    datapnt = DataPoint.objects.get(pk=dppk)
    if(request.method == 'POST'):
        form = DataPointForm(request.POST, instance=datapnt)
        if(form.is_valid()):
            form.save()
            return redirect("/consumer_datapoint/datapoint")
    else:
        form = DataPointForm(instance=datapnt)
        return render(request,'consumer_datapoint/datapoint.html',{'form':form})

@login_required
def create_datapoint(request):
    if request.method == 'POST':
        form = DataPointForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/consumer_datapoint/datapoint")
    form = DataPointForm()
    return render(request, 'consumer_datapoint/create_datapoint.html', {
        'username':request.user.username,
        'logo': 'M-PSYCH',
        'page':create_datapoint.__name__,
        'app_links':[],
        'login':"logout",
        'form':form,
    })

@login_required
def delete_datapoint(request,dppk):
    DataPoint.objects.filter(pk=dppk).delete()
    return redirect("/consumer_datapoint/datapoint/")

###########

@login_required
def datapoint_group(request):
    return render(request, 'consumer_datapoint/datapoint_group.html',{
        'username':request.user.username,
        'logo': 'M-PSYCH',
        'page':datapoint_group.__name__,
        'app_links':["datapoint", "datapoint_group", "profile"],
        'login':"logout",
    })

@login_required
def profile(request):
    return render(request, 'consumer_datapoint/profile.html',{
        'username':request.user.username,
        'logo': 'M-PSYCH',
        'page':profile.__name__,
        'app_links':["datapoint", "datapoint_group", "profile"],
        'login':"logout",
    })


# from django.http import HttpResponseRedirect
# from django.urls import reverse
# from django.contrib.auth.mixins import LoginRequiredMixin

# class ConsumerDataPointView(LoginRequiredMixin,generic.DetailView):
#     login_url = '/account/login/'
#     model = User
    # accountModel = Account
    # user_account = UserAccount
    # template_name = 'consumer_datapoint/consumer_datapoint.html'

    # context_object_name = 'username'

    # def get_context_data(self):
    #     return self.request.user
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
        # context['now'] = datetime.now()
        # return context
    #Do you have an account? No: Redirect to unknown_account page, Yes: Continue
    #Is the account active? No: Redirect to inactive_account page, Yes: Display user data on page

# class LoginView(generic.TemplateView):
#     template_name = 'consumer_datapoint/login.html'
#
# class UserAccountLandingView(generic.TemplateView):
#     template_name = 'consumer_datapoint/user_account.html'
#
# class DataPointsView(generic.TemplateView):
#     template_name = 'consumer_datapoint/datapoints.html'
#
# class DataPointView(generic.TemplateView):
#     template_name = 'consumer_datapoint/datapoint.html'
#
# class CreateDataPointView(generic.TemplateView):
#     template_name = 'consumer_datapoint/datapoints.html'
#
# class DataPointGroupsView(generic.TemplateView):
#     template_name = 'consumer_datapoint/datapoint_groups.html'
#
# class DataPointGroupView(generic.TemplateView):
#     template_name = 'consumer_datapoint/datapoint_group.html'
#
# class CreateDataPointGroupView(generic.TemplateView):
#     template_name = 'consumer_datapoint/datapoint_groups.html'
#
# class ProfilesView(generic.TemplateView):
#     template_name = 'consumer_datapoint/profiles.html'
#
# class ProfileView(generic.TemplateView):
#     template_name = 'consumer_datapoint/profile.html'
#
# class CreateProfileView(generic.TemplateView):
#     template_name = 'consumer_datapoint/profiles.html'



# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'
#
#     def get_queryset(self):
#         """Return the last five published questions."""
#         return Question.objects.order_by('-pub_date')[:5]
#
#
# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'
#
#
# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'
#
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/base_00.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{{page}}</title>
  <meta name="description" content="HTML5">
  <meta name="author" content="vostee">
  <link rel="stylesheet" type="text/css" href="{% static 'consumer_datapoint/main.css' %}">
</head>

<body>
  <!-- <script src="js/scripts.js"></script> -->
  <div id="wrapper">
    <div id="banner">
      <div id="cdp_logo">
        <b><a href="/">PSYCHI</a></b><br />
      </div>
      <div id="user_controls">
        <b>{{username}}</b><span><b> | </b></span> <a href='/{{login}}'>{{login}}</a><br />
      </div>
    </div>
    <div id="banner_shadow"></div>
    <div id="bread_crumb">
      {% block bread_crumb %}
      {% endblock %}
    </div>
    <div id="action_bar">
      {% block action_bar %}
      {% endblock %}
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
    <div id="footer">VOSTE &middot; &copy; &middot; {% now "Y" %} </div>
  </div>
</body>
</html>

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/base_01.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{{page}}</title>
  <meta name="description" content="HTML5">
  <meta name="author" content="vostee">
  <link rel="stylesheet" type="text/css" href="{% static 'consumer_datapoint/main.css' %}">
</head>

<body>
  <!-- <script src="js/scripts.js"></script> -->
  <div id="wrapper">
    <div id="banner">
      <div id="cdp_logo"><b><a href="/">{{logo}}</a></b><br /></div>
      <div id="user_controls">
        <b>{{username}}</b><span>  |  </span><a href='/{{login}}'>{{login}}</a>
      </div>
    </div>
    <div id="banner_shadow">.</div>
    <div id="content">
      {% block content %}
      {% endblock %}
      
      {% for app_link in app_links %}
          <a href="{{ app_link }}">{{ app_link }}</a><br/>
      {% endfor %}

      {% if datapoint_list %}
          <ul>
          {% for dp in datapoint_list %}
              <li><a href="{% url 'consumer_datapoint:datapoint' dp.id %}">{{ dp.datapoint }}</a></li>
          {% endfor %}
          </ul>
      {% else %}
          <!-- <p>No datapoint are available.</p> -->
      {% endif %}
    </div>
  </div>
</body>
</html>

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/consumer_datapoint.html
{% extends 'consumer_datapoint/base_00.html' %}
<!doctype html>

{% block content %}

  {% for app_link in app_links %}
      <a href="{{ app_link }}">{{ app_link }}</a><br/>
  {% endfor %}

  {% if datapoint_list %}
      <ul>
      {% for dp in datapoint_list %}
          <li><a href="{% url 'consumer_datapoint:datapoint' dp.id %}">{{ dp.datapoint }}</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <!-- <p>No datapoint are available.</p> -->
  {% endif %}
{% endblock %}

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/create_datapoint.html
{% extends 'consumer_datapoint/base_00.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% for app_link in app_links %}
    <li><a href="{{ app_link }}">{{ app_link }}</a></li>
{% endfor %}<br/>
<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <!-- {{ form | crispy }} -->
    <button type="submit">Submit</button>
</form>
{% endblock %}

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/datapoint.html
{% extends 'consumer_datapoint/base_00.html' %}
{% load crispy_forms_tags %}
{%block content %}
{% for app_link in app_links %}
    <li><a href="{{ app_link }}">{{ app_link }}</a></li>
{% endfor %}
<form method="post" action="">
    {% csrf_token %}
    {{ form }}
    <!-- {{ form | crispy }} -->
    <button type="submit">Submit</button>
</form>
{% endblock %}
<!-- <table border='1px'>
<tr><td>DATAPOINT</td><td>ANSWER_TYPE</td><td>OPTIONS</td></tr>
<tr><td>{{datapoint}}</td><td>{{ datapoint.answer_type }}</td><td>{{datapoint.options}}</td></tr>
</table> -->

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/datapoint_group.html
{% extends 'consumer_datapoint/base_00.html' %}
datapoint_group

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/datapoint_groups.html
{% extends 'consumer_datapoint/base_00.html' %}
datapoint_groups

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/datapoints.html
{% extends 'consumer_datapoint/base_00.html' %}
{% block action_bar %}
  {% for app_link in app_links %}
      <a href="/consumer_datapoint/datapoint/{{ app_link }}">{{ app_link }}</a>
  {% endfor %}
{% endblock %}

{% block content %}
{% if datapoint_list %}
    <table border="1px">
      <tr>
        <!-- <td><input id="select_all" type="checkbox"></input></td> -->
        <td>DATAPOINT</td>
        <td>TYPE</td>
      </tr>
    {% for dp in datapoint_list %}
        <tr>
          <!-- <td><input id="{{dp.id}}" type="checkbox"></input></td> -->
          <td><a href="{% url 'consumer_datapoint:datapoint' dp.id %}">{{ dp.datapoint }}</td>
          <td>{{dp.answer_type}}</a></td>
          <td><a href="{% url 'consumer_datapoint:delete_datapoint' dp.id %}">delete</td>
        </tr>
    {% endfor %}
  </table>
{% else %}
    <p>No datapoints are available.</p>
{% endif %}
{% endblock %}
<!-- Authorized_Apps <a href='/{{app_links}}'>{{app_links}}</a><br /> -->

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/index.html
{% extends 'consumer_datapoint/base_00.html' %}
{% block content %}
<a href='/{{app_links}}'>{{app_links}}</a><br />
{% endblock %}

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/login.html
{% extends 'consumer_datapoint/base_00.html' %}
{% block content %}
    <div id="login">
        <form class="form-horizontal" name="LoginForm" action="/login/" method="post">
          {% csrf_token %}
          {% if next %}
              <input type="hidden" name="next" value="{{ next }}" />
          {% endif %}
          <div id=auth_container>
            <div class="control-group">
                <label class="control-label" for="username">Username</label>
                <div class="controls">
                    <input type="text" id="username" name="username"  placeholder="Username">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="password">Password</label>
                <div class="controls">
                    <input type="password" name="password" id="password" placeholder="Password">
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn">Login</button>
                </div>
            </div>
          </div>
        </form>
    </div>
{% endblock %}

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/profile.html
{% extends 'consumer_datapoint/base_00.html' %}
{% load static %}
{% for app_link in app_links %}
    <li><a href="/consumer_datapoint/{{ app_link }}">{{ app_link }}</a></li>
{% endfor %}
<!-- Authorized_Apps <a href='/{{app_links}}'>{{app_links}}</a><br /> -->

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/profiles.html
{% extends 'consumer_datapoint/base_00.html' %}
profiles

tutorials/virtual_env/virtual_env_dir-01/site_v1/consumer_datapoint/templates/consumer_datapoint/user_account.html
{% extends 'consumer_datapoint/base_00.html' %}